[project]
name = "ftl-tool-think"
version = "0.1.0"
description = "FTL tructured reasoning tool"
authors = ["corey@coreyr.com"]
access_control = "public"

[component.think]
path = "think"
wasm = "think/target/wasm32-wasip1/release/think.wasm"
allowed_outbound_hosts = []

[component.think.build]
command = "make build"
watch = [
    "src/**/*.rs",
    "Cargo.toml",
]

[mcp]
gateway = "ghcr.io/fastertools/mcp-gateway:0.0.12"
authorizer = "ghcr.io/fastertools/mcp-authorizer:0.0.14"
validate_arguments = false
