[project]
name = "ftl-tool-think"
version = "0.1.0"
description = "FTL tool for sequential thinking and structured reasoning"
authors = ["Corey Ryan <corey@coreyr.com>"]

[auth]
enabled = false

[tools.think]
path = "think"
wasm = "target/wasm32-wasip1/release/think.wasm"
allowed_outbound_hosts = []

[tools.think.build]
command = "make build"
watch = [
    "src/**/*.rs",
    "Cargo.toml",
]

[mcp]
gateway = "ghcr.io/fastertools/mcp-gateway:0.0.9"
authorizer = "ghcr.io/fastertools/mcp-authorizer:0.0.9"
validate_arguments = true
