[project]
name = "whs"
version = "0.1.0"
description = "FTL MCP server for hosting MCP tools"
authors = []
access_control = "public"

[tools.think]
path = "think"
wasm = "think/target/wasm32-wasip1/release/think.wasm"
allowed_outbound_hosts = []

[tools.think.build]
command = "make build"
watch = [
    "src/**/*.rs",
    "Cargo.toml",
]

[mcp]
gateway = "ghcr.io/fastertools/mcp-gateway:0.0.10"
authorizer = "ghcr.io/fastertools/mcp-authorizer:0.0.12"
validate_arguments = false
