name: FTL Test

on:
  push:
    branches: [ fix-smoke-tests ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ftl-test:
    name: FTL Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: fastertools/actions/actions/setup-ftl@ba0a97f9b5103d70f4abd6c2909bd852f934bf4c
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      
      - name: Build WASM
        run: ftl build

      - uses: fastertools/actions/actions/ftl-eng-deploy@ba0a97f9b5103d70f4abd6c2909bd852f934bf4c
        env:
          FTL_M2M_APP_CLIENT_ID: ${{ secrets.FTL_M2M_APP_CLIENT_ID }}
          FTL_M2M_APP_CLIENT_SECRET: ${{ secrets.FTL_M2M_APP_CLIENT_SECRET }}
        with:
          oauth-url: https://divine-lion-50-staging.authkit.app/oauth2/token
          scope: 'FTL GitHub Deploy Action'
          wait-for-deployment: true
          deployment-timeout: 300
      
      - name: Test MCP endpoint
        run: |
          HEALTH_URL="http://localhost:3000/mcp"
          mcp_request='{"jsonrpc":"2.0","method":"ping","id":1}'
          
          mcp_response=$(curl -w "HTTP_STATUS:%{http_code}" -s --connect-timeout 5 --max-time 10 \
               -H "Content-Type: application/json" \
               -X POST \
               -d "$mcp_request" \
               "$HEALTH_URL" 2>&1)
          
          http_status=$(echo "$mcp_response" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          
          if [[ "$http_status" == "200" ]]; then
            echo "✅ MCP endpoint responding with HTTP 200"
          else
            echo "❌ MCP endpoint failed with status: $http_status"
            echo "Response: $mcp_response"
            exit 1
          fi
      