name: FTL Test

on:
  push:
    branches: [ fix-smoke-tests ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ftl-test:
    name: FTL Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: fastertools/actions/actions/setup-ftl@9a103e4e776078a08f0aeed9fc2484a28d952cbb
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      
      - name: Build WASM
        run: ftl build

      - uses: fastertools/actions/actions/start-ftl-server@9a103e4e776078a08f0aeed9fc2484a28d952cbb
      
      - name: Test MCP endpoint
        run: |
          curl -f http://localhost:8080/mcp || exit 1
          echo "✅ MCP endpoint responding"
      