name: FTL Test

on:
  push:
    branches: [ fix-smoke-tests ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ftl-test:
    name: FTL Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup FTL CLI with Dependencies
        uses: fastertools/actions/ftl-setup@9fa4e942f52c57214fdb4525fc3accb0f6fdac2d

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      
      - name: Build WASM
        run: ls -al && ftl build --export spin --export-out ./ && cat spin.toml && cat ftl.toml

      - name: Start FTL Server
        uses: fastertools/actions/ftl-server-up@9fa4e942f52c57214fdb4525fc3accb0f6fdac2d
        with:
          port: 3000
          timeout: 30

      # - uses: fastertools/actions/actions/ftl-eng-deploy@21403b8e36d45ab02cbe5fe8c0fc9951f56cb9bc
      #   env:
      #     FTL_M2M_APP_CLIENT_ID: ${{ secrets.FTL_M2M_APP_CLIENT_ID }}
      #     FTL_M2M_APP_CLIENT_SECRET: ${{ secrets.FTL_M2M_APP_CLIENT_SECRET }}
      
      - name: Test MCP endpoint
        run: |
          HEALTH_URL="http://localhost:3000/mcp"
          mcp_request='{"jsonrpc":"2.0","method":"tools/list","id":1}'
          
          mcp_response=$(curl -w "HTTP_STATUS:%{http_code}" -s --connect-timeout 5 --max-time 10 \
               -H "Content-Type: application/json" \
               -X POST \
               -d "$mcp_request" \
               "$HEALTH_URL" 2>&1)
          
          echo $mcp_response
          http_status=$(echo "$mcp_response" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          
          if [[ "$http_status" == "200" ]]; then
            echo "✅ MCP tools/list endpoint responding with HTTP 200"
            echo "Available tools:"
            echo "$mcp_response" | sed 's/HTTP_STATUS:[0-9]*//' | jq '.result.tools[]?.name' 2>/dev/null || echo "$mcp_response"
          else
            echo "❌ MCP tools/list endpoint failed with status: $http_status"
            echo "Response: $mcp_response"
            exit 1
          fi
      